### ISSUE TITLE
Not requesting launch/patient scope

### ISSUE THREAD

**Issue by burcakulug** [smart-on-fhir/cardiac-risk-app#7]
Isn't this app supposed to request launch/patient scope? It seems to be depending on patient context to exist.

**Comment by jmandel** [comment]
Technically this should request at least the `launch` scope, if not also `launch/patient`. We document  `launch/patient` as a requirement in our Standalone launch flow. Since this app uses the EHR launch flow, it doesn't specifically need to request `launch/patient`, but I think it's still a good practice to be explicit.

**Comment by burcakulug** [comment]
Thank you for the quick response. On the platform side, can you assume that if the app requests any `patient/*` kind of scope, the platform should provide or let the user to pick a `patient` context?

**Comment by vlad-ignatov** [comment]
In fact, when launched from an EHR (when `iss` and `launch` parameters are passed to the launch.html) the `fhirclient` library will automatically  add `launch` to the requested scopes if it is missing. If that library was not used, then you are correct that `lauch` scope should be added.
